<?php
/* @var $this UserController */
/* @var $model User */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List User', 'url'=>array('index')),
	array('label'=>'Create User', 'url'=>array('create')),
	array('label'=>'Update User', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete User', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage User', 'url'=>array('admin')),
);
?>

<h1>View User #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'status',
		'declien_reason',
		'first_name',
		'last_name',
		'office_location',
		'department',
		'telephone_number_desk',
		'telephone_number_cell',
		'email',
		'password',
		'date_of_birth',
		'dietary_requirements',
		'passport',
		'special_requests',
		'nationality',
		'has_guest',
		'departure_date',
		'return_date',
		'airport_name',
		'airport_code',
		'travel_policy',
		'visa_policy',
		'hotel_arrival_date',
		'hotel_departure_date',
		'hotel_venue',
		'gala_dinner',
		'other_activity',
		'created_at',
		'created_by',
		'updated_at',
		'updated_by',
		'daytime_phone',
		'evening_phone',
		'work_address1',
		'work_address2',
		'work_city',
		'work_state',
		'work_zip_code',
		'work_country',
		'managers_name',
		'emergency_contact_name',
		'emergency_contact_tel_number',
		'relationship_with_the_emergency_contact',
		'ga_passport',
		'ga_dateofbirth',
		'ga_firstname',
		'ga_lastname',
		'ga_gender',
		'ga_card_number',
		'ga_card_country',
		'ga_card_expiration_date',
		'ga_card_issue_date',
		'ga_redress_number',
		'previous_winners',
		'times',
		'years',
		'destination_city',
		'preferred_seat_request',
		'preferred_airline_frequent_flyer_number',
		'other',
		'need_visa',
		'visa_letter',
		'checked',
		'room_type',
		'room_requirements',
		'credit_card_number',
		'credit_card_expiration_date',
		'cardholders_name',
		'credit_card_type',
		'team_dinner',
		'team_dinner_menu',
		'team_dinner_dietary',
		'gala_dinner_menu',
		'gala_dinner_dietary',
		'type',
		'gender',
		'country',
		'preferred_name',
		'requirements',
		'cardholders_address',
		'csv_number',
		'crew_diet_requirements',
		'crew_other_info',
		'crew_menu_choice',
		'crew_unifrom_size',
	),
)); ?>
